name: Snapshot Builds
on: 
  push:
    branches:
      - tauri

jobs:
  build-snapshot:
    strategy:
      matrix:
        # TODO: add linux later
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Revision Hash (Linux/Bash)
        if: matrix.os == 'ubuntu-20.04'
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Get Revision Hash (Windows/Powershell)
        if: matrix.os == 'windows-latest'
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" | Add-Content -Path $env:GITHUB_ENV

      - name: Install Tauri Dependencies (Linux)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      
      - name: Set Up PNPM
        uses: pnpm/action-setup@latest
        with:
          version: ^8.9.0

      - name: Set Up Node.JS Environment
        uses: actions/setup-node@master
        with:
          node-version: 17
          cache: 'pnpm'

      - name: Install Dependencies from NPM
        run: pnpm i

      - name: Compile Application
        run: pnpm run tauri build
      
      - name: Upload Snapshot (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: SNAPSHOT-${{ env.SHA_SHORT }}-node-studio-windows-x64
          path: src-tauri/target/release/bundle/msi
      
      - name: Upload Snapshot (Linux)
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          # TODO: i honestly have no idea if this is the correct path
          # consider this a placeholder more than anything else
          name: SNAPSHOT-${{ env.SHA_SHORT }}-node-studio-linux-x64
          path: src-tauri/target/release/bundle/deb