name: Snapshot Builds
on: [push]

jobs:
  build-snapshot:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get revision hash
        id: getrev
        #run: echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT"
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up Node.JS environment
        uses: actions/setup-node@master
        with:
          node-version: 17

      - name: Install Dependencies
        run: npm install

      - name: Begin Compiling
        run: npm run tauri build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Snapshot
        uses: actions/upload-artifact@v3
        with:
          name: SNAPSHOT-${{ process.env.SHA_SHORT }}-node-studio-windows-x64
          path: src-tauri/target/release/bundle/msi