name: Snapshot Builds
on: [push]

jobs:
  build-snapshot:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get revision hash
        id: getrev
        #run: echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"
        run: $SHA = (git rev-parse --short HEAD)
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Node.JS environment
        uses: actions/setup-node@master
        with:
          node-version: 17

      - name: Install Dependencies
        run: npm install

      - name: Begin Compiling
        run: npm run tauri build
      
      - name: Upload Snapshot
        uses: actions/upload-artifact@v3
        with:
          name: SNAPSHOT-${{ $SHA }}-node-studio-windows-x64
          path: src-tauri/target/release/bundle/msi