name: Build
on: [push]

git_hash=$(git rev-parse --short "$GITHUB_SHA")

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 17
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: SNAPSHOT-${{ git_hash }}-NightlyNodeStudio-win32-x64
        path: build/node-studio-win32-x64
