name: Build
on: [push, pull_request]

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 17
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        path: build/node-studio-win32-x64
